### PR TITLE
refactor Screenshot class

### PR DESCRIPTION
**Pull request by akamarouski**
improve logic of screenshot, give more parameters to control, deprecate old methods

### CODE REVIEW

**Comment by akamarouski** [comment]
8.0.5.2007-SCREENSHOT-SNAPSHOT

**Comment by akamarouski** [comment]
Added the possibility of more complete control over screenshots, simplified / shortened interface for creating screenshots

**Comment by akamarouski** [comment]
todo: add opportunity to add rule for thread only

**Comment by okamara** [comment]
Verified during regression, fixed

**Pull request merged**
